version: '3.4'
services:
  prysm-beacon-chain.public.dappnode.eth:
    image: 'prysm-beacon-chain.public.dappnode.eth:0.1.18'
    build:
      context: ./build
      args:
        - VERSION
    volumes:
      - 'data:/data'
    ports:
      - '4000:4000'
    restart: always
    environment:
      - EXTRA_OPTS
volumes:
  data: {}
